<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">

    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="big-data-style.css">
    <title>Poly Blog</title>
</head>
<body>
    
  <section class="big-data-header">
    
        <a href="index.php"><img src="images/logoPML.png"></a>
        <div class="nav-links" id="navLinks">
            <i class="fa fa-times" onclick="hideMenu()"></i>
            <ul>
                <li><a href="index.php">HOME</a></li>
                <li><a href="courses.php">COURSES</a></li>
                <li><a href="blog_user.php">BLOG</a></li>
                <li><a href="event_user.php">EVENT</a></li>
                <li><a href="about_us.php">ABOUT</a></li>
                <li><a href="contact.php">CONTACT</a></li>
            </ul>
        </div>
        <i class="fa fa-bars" onclick="showMenu()"></i>
    

  </section>

<!---This is for the Big-Data Course-->

<section class="big-data-container">
    <h1>Big Data Analytics</h1>
    <div class="row">
        <div class="big-data-container-col">
            <img src="images/bigdata3.jpg">
            <h3>What Is Big Data Analytics</h3>
            <br>
            <P>Big Data is generated by humans. 
                In a context where not only humans interact with technology to create data, 
                but also machines interact with each other, it is thanks to the human-created 
                Big Data that the elements of the IoT are able to act intelligently and become more sophisticated.
            </P>
            <br>
            <a href="https://poly.ac.mu/it-emerging-technologies/diploma-in-information-technology-big-data-analytics/" target="_blank" class="big-data-btn">Click Here To Know More</a>
        </div>
        <div class="big-data-container-col">
            <iframe width="470" height="310" src="https://www.youtube.com/embed/bAyrObl7TYE" title="YouTube video player" frameborder="0" 
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <h3>A Video About What is Big Data</h3>
            
        </div>
        <div class="big-data-container-col">
            <img src="images/bigdata1.jpg">
            <h3>Career Opportunities In Big Data Analytics</h3>
            <ul>
                <li>• Data Scientist</li>
                <br>
                <li>• Data Engineer</li>
                <br>
                <li>• Data Analyst</li>
                <br>
                <li>• Security Engineer</li>
                <br>
                <li>• Database Manager</li>
            </ul>
            <br>
            <a href="https://poly.ac.mu/it-emerging-technologies/diploma-in-information-technology-big-data-analytics/" target="_blank" class="big-data-btn">Click Here To Know More</a>
        </div>
    </div>
</section>

<script>
        var navLinks = document.getElementById("navLinks")
        function showMenu(){
            navLinks.style.right = "0";
        }
        function hideMenu(){
            navLinks.style.right = "-200px";
        }

</script>
    
</body>
</html>